In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [2]:
mnist = fetch_openml('mnist_784')

C:\Users\NP\AppData\Roaming\Python\Python39\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
mnist

{'data':        pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
 0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 ...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
 69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
 
      

In [4]:
X = mnist.data.astype('float32')
y = mnist.target.astype('int64')

X /= 255.0

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 1. Logistic Regression classifier from scikit-learn

In [5]:
clf = LogisticRegression(max_iter=1000, random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)

print("Logistic Regression Accuracy: {:.4f}".format(acc))
print("Logistic Regression Confusion Matrix:")
print(conf_mat)

Logistic Regression Accuracy: 0.9208
Logistic Regression Confusion Matrix:
[[1294    1    7    0    3   13   13    4    6    2]
 [   0 1550    6   10    3   12    0    4   13    2]
 [   5   20 1234   21   15    9   20   17   29   10]
 [   6    9   30 1282    1   39    7   18   23   18]
 [   6    3    6    4 1201    5   11    8    7   44]
 [   4   10    7   41   12 1125   20    4   36   14]
 [   5    4   19    1   14   17 1331    2    3    0]
 [   6    4   26    3   11    6    0 1415    1   31]
 [  10   26   13   44    6   42    9    9 1178   20]
 [   7   11    6   13   36    7    0   44   15 1281]]


## 2. Support Vector Machine (SVM) classifier

In [7]:
from sklearn.svm import SVC

svm = SVC(C=1.0, kernel='rbf', random_state=42)
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

acc_svm = accuracy_score(y_test, y_pred_svm)
conf_mat_svm = confusion_matrix(y_test, y_pred_svm)

print("SVM Accuracy: {:.4f}".format(acc_svm))
print("SVM Confusion Matrix:")
print(conf_mat_svm)

SVM Accuracy: 0.9764
SVM Confusion Matrix:
[[1329    1    3    0    1    2    2    1    4    0]
 [   0 1585    4    3    2    0    0    4    2    0]
 [   3    4 1348    2    3    2    4    8    5    1]
 [   0    2   11 1386    2   11    1    9    7    4]
 [   1    0    2    0 1269    0    3    2    2   16]
 [   0    1    2   15    2 1236    9    1    7    0]
 [   1    0    0    0    4    4 1384    0    3    0]
 [   1    6   12    1    5    1    0 1465    1   11]
 [   2    6    8   12    4    9    6    4 1303    3]
 [   5    8    2    8   14    2    0   11    5 1365]]


## 3. Random Forest Classifier

In [8]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_rf)
conf_mat_rf = confusion_matrix(y_test, y_pred_rf)

print("Random Forest Accuracy: {:.4f}".format(acc_rf))
print("Random Forest Confusion Matrix:")
print(conf_mat_rf)


Random Forest Accuracy: 0.9675
Random Forest Confusion Matrix:
[[1325    0    4    0    1    1    3    1    6    2]
 [   0 1573    6    8    2    0    0    6    3    2]
 [   3    5 1335    4    5    1    9    8    8    2]
 [   1    0   23 1366    0    9    0   14   12    8]
 [   4    1    3    0 1256    0    2    3    3   23]
 [   1    3    3   17    4 1226    8    1    8    2]
 [   4    1    0    0    6   10 1372    0    3    0]
 [   3    5   15    0    7    1    0 1455    2   15]
 [   1    6    8   15    5   10    5    7 1293    7]
 [   4    6    5   16   20    5    1   10    9 1344]]


## 4. K-Nearest Neighbors (KNN) classifier

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

acc_knn = accuracy_score(y_test, y_pred_knn)
conf_mat_knn = confusion_matrix(y_test, y_pred_knn)

print("KNN Accuracy: {:.4f}".format(acc_knn))
print("KNN Confusion Matrix:")
print(conf_mat_knn)


KNN Accuracy: 0.9713
KNN Confusion Matrix:
[[1335    0    5    0    0    0    1    1    1    0]
 [   0 1591    3    0    1    1    0    3    0    1]
 [   8   14 1333    1    1    1    4   13    3    2]
 [   0    3   12 1382    0   10    2   10    7    7]
 [   3    9    1    0 1248    0    2    4    1   27]
 [   4    5    0   13    4 1234   12    0    1    0]
 [   5    1    0    0    4    3 1383    0    0    0]
 [   1   17    4    0    2    0    0 1467    1   11]
 [   6   13    8   21    4   16    3    6 1269   11]
 [   6    6    3   14   20    0    0   14    1 1356]]


## 5. Naive Bayes Classifier

In [10]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

acc_nb = accuracy_score(y_test, y_pred_nb)
conf_mat_nb = confusion_matrix(y_test, y_pred_nb)

print("Naive Bayes Accuracy: {:.4f}".format(acc_nb))
print("Naive Bayes Confusion Matrix:")
print(conf_mat_nb)

Naive Bayes Accuracy: 0.5516
Naive Bayes Confusion Matrix:
[[1218    2    9    2    4    2   52    2   32   20]
 [   2 1520    3    5    0    4   15    1   39   11]
 [ 142   40  408  102    5    5  331    0  327   20]
 [ 118   66   12  462    2    8   90    9  496  170]
 [  51    7   15    6  170    7  146    5  278  610]
 [ 183   31   10   18    4   56   77    3  757  134]
 [  16   25    6    0    2    4 1316    0   24    3]
 [   8   10    3   16    8    3    1  417   50  987]
 [  28  160    5    9    3    3   30    3  816  300]
 [   9    8    7    4    8    0    1   20   24 1339]]


## 6. Decision Tree Classifier

In [11]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=10, random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

acc_dt = accuracy_score(y_test, y_pred_dt)
conf_mat_dt = confusion_matrix(y_test, y_pred_dt)

print("Decision Tree Accuracy: {:.4f}".format(acc_dt))
print("Decision Tree Confusion Matrix:")
print(conf_mat_dt)

Decision Tree Accuracy: 0.8583
Decision Tree Confusion Matrix:
[[1253    2   17    5    5   12   22    4   14    9]
 [   3 1516    5   21   20    9    5    7    9    5]
 [  26   34 1126   25   23   16   16   20   63   31]
 [   6   13   37 1173   16   83   10   20   39   36]
 [   6   10    9   12 1084   19   15   12   18  110]
 [  36   18   15   72   16 1030   22    4   37   23]
 [  26   16   20    5   20   26 1242    4   26   11]
 [   4   14   30   43   16    6    1 1318   23   48]
 [  11   38   36   50   25   34   19   17 1072   55]
 [  11   11   16   25   75   29    8   27   16 1202]]


## 7. Gradient Boosting Classifier

In [12]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

acc_gb = accuracy_score(y_test, y_pred_gb)
conf_mat_gb = confusion_matrix(y_test, y_pred_gb)

print("Gradient Boosting Accuracy: {:.4f}".format(acc_gb))
print("Gradient Boosting Confusion Matrix:")
print(conf_mat_gb)

Gradient Boosting Accuracy: 0.9454
Gradient Boosting Confusion Matrix:
[[1314    1    3    2    2    2    6    1   12    0]
 [   0 1572    5    5    4    3    0    5    4    2]
 [   4    7 1304    8   11    1   10   10   19    6]
 [   2    8   21 1317    1   29    1   16   17   21]
 [   2    1    7    3 1227    1    5    4    3   42]
 [   6    7    5   29    8 1183   10    1   18    6]
 [   4    3    5    0   14   17 1344    0    9    0]
 [   6    8   16    4    8    3    0 1418    3   37]
 [   4    9   10   22    8   18    7    7 1253   19]
 [   7    9    4   19   25    7    1   34   10 1304]]


## 8. Simple Neural Network using Keras

In [13]:
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(784,)),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, validation_split=0.1)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Neural Network Accuracy: {:.4f}".format(test_acc))


Epoch 1/10
1575/1575 [==============================] - 5s 2ms/step - loss: 0.3199 - accuracy: 0.9089 - val_loss: 0.1791 - val_accuracy: 0.9482
Epoch 2/10
1575/1575 [==============================] - 2s 2ms/step - loss: 0.1506 - accuracy: 0.9553 - val_loss: 0.1289 - val_accuracy: 0.9639
Epoch 3/10
1575/1575 [==============================] - 2s 1ms/step - loss: 0.1074 - accuracy: 0.9675 - val_loss: 0.1077 - val_accuracy: 0.9657
Epoch 4/10
1575/1575 [==============================] - 2s 2ms/step - loss: 0.0842 - accuracy: 0.9745 - val_loss: 0.1014 - val_accuracy: 0.9680
Epoch 5/10
1575/1575 [==============================] - 2s 2ms/step - loss: 0.0682 - accuracy: 0.9796 - val_loss: 0.0888 - val_accuracy: 0.9729
Epoch 6/10
1575/1575 [==============================] - 2s 1ms/step - loss: 0.0577 - accuracy: 0.9829 - val_loss: 0.0930 - val_accuracy: 0.9739
Epoch 7/10
1575/1575 [==============================] - 2s 1ms/step - loss: 0.0486 - accuracy: 0.9854 - val_loss: 0.0928 - val_accuracy:

## 9. Multilayer Perceptron (MLP) Neural Network

In [14]:
mlp = keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=(784,)),
    layers.Dropout(0.2),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(10, activation='softmax')
])

mlp.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

mlp.fit(X_train, y_train, epochs=10, validation_split=0.1)

test_loss_mlp, test_acc_mlp = mlp.evaluate(X_test, y_test)
print("MLP Accuracy: {:.4f}".format(test_acc_mlp))


Epoch 1/10
1575/1575 [==============================] - 7s 4ms/step - loss: 0.2347 - accuracy: 0.9286 - val_loss: 0.1077 - val_accuracy: 0.9686
Epoch 2/10
1575/1575 [==============================] - 8s 5ms/step - loss: 0.1093 - accuracy: 0.9663 - val_loss: 0.0954 - val_accuracy: 0.9709
Epoch 3/10
1575/1575 [==============================] - 9s 6ms/step - loss: 0.0827 - accuracy: 0.9735 - val_loss: 0.0926 - val_accuracy: 0.9732
Epoch 4/10
1575/1575 [==============================] - 9s 6ms/step - loss: 0.0681 - accuracy: 0.9787 - val_loss: 0.0843 - val_accuracy: 0.9737
Epoch 5/10
1575/1575 [==============================] - 9s 6ms/step - loss: 0.0560 - accuracy: 0.9824 - val_loss: 0.0825 - val_accuracy: 0.9750
Epoch 6/10
1575/1575 [==============================] - 9s 6ms/step - loss: 0.0506 - accuracy: 0.9836 - val_loss: 0.0830 - val_accuracy: 0.9773
Epoch 7/10
1575/1575 [==============================] - 9s 6ms/step - loss: 0.0443 - accuracy: 0.9857 - val_loss: 0.0706 - val_accuracy:

## 10. Convolutional Neural Network (CNN) using Keras

In [17]:
X_train_cnn = np.array(X_train).reshape(-1, 28, 28, 1)
X_test_cnn = np.array(X_test).reshape(-1, 28, 28, 1)

model_cnn = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model_cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_cnn.fit(X_train_cnn, y_train, epochs=10, validation_split=0.1)

test_loss_cnn, test_acc_cnn = model_cnn.evaluate(X_test_cnn, y_test)
print("CNN Accuracy: {:.4f}".format(test_acc_cnn))

Epoch 1/10
1575/1575 [==============================] - 27s 17ms/step - loss: 0.1540 - accuracy: 0.9530 - val_loss: 0.0503 - val_accuracy: 0.9861
Epoch 2/10
1575/1575 [==============================] - 30s 19ms/step - loss: 0.0508 - accuracy: 0.9844 - val_loss: 0.0427 - val_accuracy: 0.9875
Epoch 3/10
1575/1575 [==============================] - 29s 19ms/step - loss: 0.0358 - accuracy: 0.9884 - val_loss: 0.0341 - val_accuracy: 0.9895
Epoch 4/10
1575/1575 [==============================] - 30s 19ms/step - loss: 0.0267 - accuracy: 0.9920 - val_loss: 0.0410 - val_accuracy: 0.9891
Epoch 5/10
1575/1575 [==============================] - 30s 19ms/step - loss: 0.0206 - accuracy: 0.9936 - val_loss: 0.0332 - val_accuracy: 0.9911
Epoch 6/10
1575/1575 [==============================] - 30s 19ms/step - loss: 0.0160 - accuracy: 0.9949 - val_loss: 0.0405 - val_accuracy: 0.9889
Epoch 7/10
1575/1575 [==============================] - 31s 20ms/step - loss: 0.0117 - accuracy: 0.9963 - val_loss: 0.0360 -

In [18]:
model_cnn_bn = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(10, activation='softmax')
])

model_cnn_bn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_cnn_bn.fit(X_train_cnn, y_train, epochs=10, validation_split=0.1)

test_loss_cnn_bn, test_acc_cnn_bn = model_cnn_bn.evaluate(X_test_cnn, y_test)
print("CNN with Batch Normalization Accuracy: {:.4f}".format(test_acc_cnn_bn))


Epoch 1/10
1575/1575 [==============================] - 43s 26ms/step - loss: 0.1072 - accuracy: 0.9691 - val_loss: 0.0427 - val_accuracy: 0.9880
Epoch 2/10
1575/1575 [==============================] - 44s 28ms/step - loss: 0.0478 - accuracy: 0.9862 - val_loss: 0.0387 - val_accuracy: 0.9861
Epoch 3/10
1575/1575 [==============================] - 44s 28ms/step - loss: 0.0333 - accuracy: 0.9899 - val_loss: 0.0353 - val_accuracy: 0.9902
Epoch 4/10
1575/1575 [==============================] - 44s 28ms/step - loss: 0.0273 - accuracy: 0.9913 - val_loss: 0.0310 - val_accuracy: 0.9909
Epoch 5/10
1575/1575 [==============================] - 45s 29ms/step - loss: 0.0195 - accuracy: 0.9939 - val_loss: 0.0315 - val_accuracy: 0.9900
Epoch 6/10
1575/1575 [==============================] - 44s 28ms/step - loss: 0.0155 - accuracy: 0.9948 - val_loss: 0.0326 - val_accuracy: 0.9912
Epoch 7/10
1575/1575 [==============================] - 44s 28ms/step - loss: 0.0148 - accuracy: 0.9953 - val_loss: 0.0491 -